### ISSUE TITLE
ALB integration?

### ISSUE THREAD

**Issue by 0xdabbad00** [alloy-commons/alloy-open-source#38] opened 2020-02-03 18:58 UTC
Based on https://medium.com/@alsmola/alb-authentication-with-g-suite-saml-using-cognito-858e35564dc8, by @alsmola, it sounds like the gsuite-saml-cognito part of this repo (https://github.com/alloy-commons/alloy-open-source/blob/master/terraform-modules/gsuite-saml-cognito/README.md) cannot actually be used for ALB authentication. Is that correct?  Can you provide a POC to further show the integration?

**Comment by alex** [comment] 2020-02-03 19:02
Hey Scott,

It absolutely can be (that's what we wrote it for). I have a TODO to open source our ALB module, but here's the relevant block:

```hcl
variable "cognito_user_pool" {
  type        = object({ arn = string, client_id = string, domain = string })
  default     = null
  description = "Cognito user pool ARN, ID, and domain that will be used to authenticate users"
}

resource "aws_lb_listener" "https" {
  load_balancer_arn = aws_lb.load_balancer.arn
  port              = 443
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS-1-2-2017-01"
  certificate_arn   = module.lb_certificate.acm_certificate_arn

  dynamic "default_action" {
    for_each = var.cognito_user_pool == null ? [] : [for c in [var.cognito_user_pool] : {
      arn    = c.arn
      id     = c.client_id
      domain = c.domain
    }]
    iterator = cognito

    content {
      type = "authenticate-cognito"

      authenticate_cognito {
        user_pool_arn       = cognito.value.arn
        user_pool_client_id = cognito.value.id
        user_pool_domain    = cognito.value.domain
      }
    }
  }

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.application.arn
  }
}
```

(Bonus meta programming since we use our ALB for two different things)

**Comment by 0xdabbad00** [comment] 2020-02-03 19:09
Thank you @alex. Hopefully Alex Smolen can chime in to see if that helps resolve his issues.

**Comment by alex** [comment] 2020-02-03 19:28
Cool. I'm going to close this on the theory that this was the missing piece :-) If it's not, please leave a comment and I'll reopen!

**Closed by alex** 2020-02-03 19:28 UTC

**Comment by alsmola** [comment] 2020-02-03 21:26
Hey! Thanks @0xdabbad00 for filing, but the issue is a) ALBs send JWTs with Base64-style padding and b) a widely-used JSON signature node module (https://github.com/brianloveswords/node-jws) has strict parsing that rejects them.

If you use a more forgiving JWT parser/validator, you should be fine. So, nothing to be done on this project, but hopefully AWS can transition to a spec-compliant encoding mechanism.

**Comment by alex** [comment] 2020-02-03 21:39
Yeah, fixing that is beyond my abilities :-)
